/**
 * Stripe scaffolding — the three files we drop into a Convex-backed project's
 * sandbox the first time initializeStripePayments resolves to connected /
 * already-connected.
 *
 * Two of these files (platformStripe.ts, stripeWebhook.ts) are intended to
 * remain untouched after generation — the agent's write-guards enforce that.
 * The third (billing.ts) is the agent's editable surface for reacting to
 * Stripe events (e.g. flipping a user row from "free" to "pro").
 *
 * The scaffolding also sets four env vars on the project's Convex deployment:
 *   BOTFLOW_PROJECT_ID
 *   BOTFLOW_STRIPE_PROXY_BASE
 *   BOTFLOW_STRIPE_WEBHOOK_SECRET
 *   STRIPE_MODE
 * so the scaffolded actions can reach the platform proxy and verify webhooks
 * without the agent needing to wire any of that up.
 */
import { eq } from 'drizzle-orm';
import { getDb } from '@/db';
import { projects } from '@/db/schema';
import { sandboxWriteFile } from '@/lib/vercel-sandbox';
import type { StripeMode } from '@/lib/stripe';

// ───────────────────────── templates ──────────────────────────

export const PLATFORM_STRIPE_TS = `// AUTO-GENERATED by Botflow. Do not edit — the agent's write-guard will refuse changes.
//
// Stripe Connect (Standard) helper. Calls back to Botflow's platform proxy,
// which uses the platform's master Stripe key with the Stripe-Account header
// to act on behalf of the user's connected account.
//
// The agent imports these actions and calls them from React (e.g. a "Buy"
// button calls createCheckoutSession, then redirects window.location to the
// returned url).
"use node";

import { action } from "./_generated/server";
import { v } from "convex/values";

const PROJECT_ID = process.env.BOTFLOW_PROJECT_ID;
const PROXY_BASE = process.env.BOTFLOW_STRIPE_PROXY_BASE ?? "https://botflow.io";
const PROJECT_SECRET = process.env.BOTFLOW_STRIPE_WEBHOOK_SECRET;
const MODE = (process.env.STRIPE_MODE ?? "test") as "test" | "live";

function requireConfigured() {
  if (!PROJECT_ID || !PROJECT_SECRET) {
    throw new Error(
      "Stripe is not initialized for this project. Ask the user to run 'set up Stripe' in chat.",
    );
  }
}

/**
 * Create a Stripe Checkout Session for the configured connected account.
 * Returns { url } — redirect the user there with window.location.assign(url).
 */
export const createCheckoutSession = action({
  args: {
    priceId: v.string(),
    successUrl: v.string(),
    cancelUrl: v.string(),
    customerEmail: v.optional(v.string()),
    quantity: v.optional(v.number()),
    metadata: v.optional(v.any()),
    /** 'payment' for one-time, 'subscription' for recurring. Default 'payment'. */
    checkoutMode: v.optional(v.string()),
  },
  handler: async (_ctx, args) => {
    requireConfigured();
    const res = await fetch(
      \`\${PROXY_BASE}/api/projects/\${PROJECT_ID}/stripe/checkout-session\`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "X-Botflow-Project-Secret": PROJECT_SECRET!,
        },
        body: JSON.stringify({ ...args, mode: MODE }),
      },
    );
    if (!res.ok) {
      const text = await res.text();
      throw new Error(\`Stripe checkout failed (\${res.status}): \${text}\`);
    }
    const data = (await res.json()) as { url: string; sessionId: string };
    return data;
  },
});

/**
 * Generate a one-time login link into the connected account's Stripe Dashboard.
 * Use this for "Open Stripe Dashboard" buttons.
 */
export const createDashboardLoginLink = action({
  args: {},
  handler: async () => {
    requireConfigured();
    const res = await fetch(
      \`\${PROXY_BASE}/api/projects/\${PROJECT_ID}/stripe/dashboard-link\`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "X-Botflow-Project-Secret": PROJECT_SECRET!,
        },
        body: JSON.stringify({ mode: MODE }),
      },
    );
    if (!res.ok) {
      const text = await res.text();
      throw new Error(\`Stripe dashboard link failed (\${res.status}): \${text}\`);
    }
    const data = (await res.json()) as { url: string };
    return data;
  },
});
`;

export const STRIPE_WEBHOOK_TS = `// AUTO-GENERATED by Botflow. Do not edit — the agent's write-guard will refuse changes.
//
// Convex HTTP endpoint that receives normalized Stripe events forwarded by
// the Botflow platform. Verifies the HMAC signature (so randoms can't spoof
// events), then hands off to billing.ts (which IS editable — that's where
// the agent writes "free → pro" mutations etc).
//
// To wire this up, ensure convex/http.ts contains:
//
//   import { httpRouter } from "convex/server";
//   import { stripeWebhook } from "./stripeWebhook";
//   const http = httpRouter();
//   http.route({ path: "/stripe/webhook", method: "POST", handler: stripeWebhook });
//   export default http;
import { httpAction } from "./_generated/server";
import { internal } from "./_generated/api";

const PROJECT_SECRET = process.env.BOTFLOW_STRIPE_WEBHOOK_SECRET;

async function hmacHex(secret: string, message: string): Promise<string> {
  const enc = new TextEncoder();
  const key = await crypto.subtle.importKey(
    "raw",
    enc.encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"],
  );
  const sig = await crypto.subtle.sign("HMAC", key, enc.encode(message));
  return Array.from(new Uint8Array(sig))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

function safeEqual(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let mismatch = 0;
  for (let i = 0; i < a.length; i++) mismatch |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return mismatch === 0;
}

export const stripeWebhook = httpAction(async (ctx, req) => {
  if (!PROJECT_SECRET) {
    return new Response("Stripe integration not configured", { status: 500 });
  }
  const signatureHeader = req.headers.get("X-Botflow-Signature");
  if (!signatureHeader) return new Response("missing signature", { status: 401 });

  const raw = await req.text();
  const expected = await hmacHex(PROJECT_SECRET, raw);
  if (!safeEqual(signatureHeader, expected)) {
    return new Response("bad signature", { status: 401 });
  }

  let event: { type: string; id: string; data?: unknown };
  try {
    event = JSON.parse(raw);
  } catch {
    return new Response("invalid json", { status: 400 });
  }

  await ctx.runMutation(internal.billing.applyStripeEvent, { event });
  return new Response("ok", { status: 200 });
});
`;

export const BILLING_TS = `// EDITABLE — this is where you implement how Stripe events change your
// project's database. The webhook receiver (stripeWebhook.ts) calls
// applyStripeEvent below with a normalized event payload.
//
// Common event types you'll handle:
//   subscription.activated  — user paid; flip them to a paid tier
//   subscription.canceled   — user cancelled; revert tier on period end
//   subscription.updated    — plan change; update the stored plan
//   payment.succeeded       — one-time payment cleared
//   payment.failed          — retry / notify
//
// The event payload's shape mirrors Stripe events but is normalized — see
// docs.stripe.com/api/events.

import { internalMutation } from "./_generated/server";
import { v } from "convex/values";

export const applyStripeEvent = internalMutation({
  args: { event: v.any() },
  handler: async (ctx, { event }) => {
    // TODO: replace this with real logic that updates your schema.
    // Example for a "users" table with a 'tier' field:
    //
    //   const email = event.data?.customer_email as string | undefined;
    //   if (!email) return;
    //   const user = await ctx.db
    //     .query("users")
    //     .withIndex("by_email", (q) => q.eq("email", email))
    //     .unique();
    //   if (!user) return;
    //   if (event.type === "subscription.activated") {
    //     await ctx.db.patch(user._id, { tier: "pro" });
    //   } else if (event.type === "subscription.canceled") {
    //     await ctx.db.patch(user._id, { tier: "free" });
    //   }
    console.log("[stripeWebhook] received", event.type, event.id);
  },
});
`;

// ───────────────────────── apply to sandbox ──────────────────────────

/**
 * Drop the three Stripe files into the project's sandbox. Idempotent —
 * platformStripe.ts and stripeWebhook.ts are always overwritten (read-only
 * by intent), while billing.ts is only created if it doesn't already exist
 * (the agent edits it).
 *
 * Returns the list of paths actually written.
 */
export async function dropStripeFilesIntoSandbox(projectId: string): Promise<string[]> {
  const { sandboxReadFile } = await import('@/lib/vercel-sandbox');
  const written: string[] = [];

  // Always re-write the two read-only files. Safe — the agent's guard refuses
  // *user* edits, but our scaffolder is the source of truth.
  await sandboxWriteFile(projectId, '/convex/platformStripe.ts', PLATFORM_STRIPE_TS);
  written.push('/convex/platformStripe.ts');
  await sandboxWriteFile(projectId, '/convex/stripeWebhook.ts', STRIPE_WEBHOOK_TS);
  written.push('/convex/stripeWebhook.ts');

  // Only seed billing.ts if missing — the agent owns this file.
  const existing = await sandboxReadFile(projectId, '/convex/billing.ts').catch(() => null);
  if (!existing || !existing.content) {
    await sandboxWriteFile(projectId, '/convex/billing.ts', BILLING_TS);
    written.push('/convex/billing.ts');
  }
  return written;
}

/** Promise.race-with-timeout, never throws — rejects-to-error are caught. */
function withTimeout<T>(p: Promise<T>, ms: number, label: string): Promise<T> {
  return Promise.race([
    p,
    new Promise<T>((_, rej) => setTimeout(() => rej(new Error(`${label} timed out after ${ms}ms`)), ms)),
  ]);
}

/**
 * Set the Convex env vars the scaffolded files read. Idempotent. Mirrors
 * setEnvVarsViaDeployKey in convex-auth-setup.ts.
 */
export async function setStripeConvexEnv(
  projectId: string,
  opts: { mode: StripeMode; webhookSecret: string; proxyBase?: string },
): Promise<{ ok: true } | { ok: false; error: string }> {
  const db = getDb();
  const [project] = await db.select().from(projects).where(eq(projects.id, projectId));
  if (!project) return { ok: false, error: 'Project not found' };

  const deployUrl = project.backendType === 'user' ? project.userConvexUrl : project.convexDeployUrl;
  const deployKey = project.backendType === 'user' ? project.userConvexDeployKey : project.convexDeployKey;
  if (!deployUrl || !deployKey) {
    return { ok: false, error: 'Convex deployment is not configured for this project' };
  }

  const vars = {
    BOTFLOW_PROJECT_ID: projectId,
    BOTFLOW_STRIPE_PROXY_BASE: opts.proxyBase ?? 'https://botflow.io',
    BOTFLOW_STRIPE_WEBHOOK_SECRET: opts.webhookSecret,
    STRIPE_MODE: opts.mode,
  };
  const changes = Object.entries(vars).map(([name, value]) => ({ name, value }));
  const res = await fetch(`${deployUrl}/api/update_environment_variables`, {
    method: 'POST',
    headers: { Authorization: `Convex ${deployKey}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ changes }),
  });
  if (!res.ok) {
    const text = await res.text();
    return { ok: false, error: `Failed to set Convex env (${res.status}): ${text.slice(0, 300)}` };
  }
  return { ok: true };
}

/**
 * One-call helper: drop the files AND set the env vars. The initialize
 * endpoint calls this on connected / already-connected transitions.
 * Failures are logged but non-fatal — the agent can run the scaffold
 * manually if needed.
 */
export async function scaffoldStripeIntoProject(
  projectId: string,
  opts: { mode: StripeMode; webhookSecret: string; proxyBase?: string },
): Promise<{
  filesWritten: string[];
  envSet: boolean;
  envError?: string;
  filesError?: string;
}> {
  // Per-operation timeouts: a cold Vercel Sandbox can take 30s+ to provision,
  // and we don't want to block the agent's tool call that long. If file drop
  // times out we return early with filesError noted — the agent can retry
  // (idempotent) or proceed and let `convex_deploy` fail naturally.
  let filesWritten: string[] = [];
  let filesError: string | undefined;
  try {
    filesWritten = await withTimeout(
      dropStripeFilesIntoSandbox(projectId),
      15_000,
      'dropStripeFilesIntoSandbox',
    );
  } catch (err) {
    filesError = err instanceof Error ? err.message : String(err);
    console.error('[stripe-scaffold] file drop failed:', err);
  }

  const envResult = await withTimeout(
    setStripeConvexEnv(projectId, opts),
    10_000,
    'setStripeConvexEnv',
  ).catch((err) => ({
    ok: false as const,
    error: err instanceof Error ? err.message : String(err),
  }));
  return {
    filesWritten,
    envSet: envResult.ok === true,
    ...(envResult.ok === true ? {} : { envError: envResult.error }),
    ...(filesError ? { filesError } : {}),
  };
}
