/**
 * Tool-name + input-shape mapping between Claude Code and the Botflow agents.
 *
 * Why this exists: a single conversation can be served by either agent (Botflow
 * uses the AI SDK with our own tool surface; Claude Code uses Anthropic's
 * Agent SDK with its own built-in tool surface). The two surfaces overlap in
 * intent but differ in name (`read` vs `Read`) and arg shape (`path` vs
 * `file_path`). If we let Claude Code's tool_use blocks flow into Botflow's
 * API request unchanged, Anthropic rejects with `messages.X.content.Y.tool_use`
 * because the names don't match any registered tool.
 *
 * This map is consulted client-side in `AgentPanel`'s
 * `prepareSendMessagesRequest` to rewrite foreign tool_use blocks into the
 * receiving agent's vocabulary before each request.
 *
 * Convention:
 *  - Tools that exist on BOTH sides with identical names + shapes (the new
 *    workspace control tools: startDevServer, stopDevServer, etc.) get a
 *    "passthrough" entry — same name, identity input transform.
 *  - Tools that exist on both sides under different names get a `to` + input
 *    transform.
 *  - Claude-Code-only tools (Task, TodoWrite, WebFetch, WebSearch, Bash sub-
 *    operations, etc.) get `null` — `prepareSendMessagesRequest` collapses
 *    those tool_use/tool_result pairs into a text-only summary so the
 *    receiving agent has prose context but doesn't try to replay them.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

export interface ToolRewrite {
  /** Renamed tool. */
  to: string;
  /** Transform the input dict from source shape to target shape. */
  mapInput: (input: any) => Record<string, any>;
}

/** No rewrite needed — same name + same input shape across agents. */
const passthrough = (name: string): ToolRewrite => ({
  to: name,
  mapInput: (i) => i ?? {},
});

const identityInput = (i: any) => i ?? {};

/**
 * Claude Code → Botflow.
 * Applied when the current backend is Botflow and we encounter a tool_use
 * generated by Claude Code in the history.
 */
export const CLAUDE_CODE_TO_BOTFLOW: Record<string, ToolRewrite | null> = {
  // ── File / search primitives (rename + shape rewrite) ────────────────
  Read: {
    to: "read",
    mapInput: (i) => ({ path: i.file_path }),
  },
  Write: {
    to: "write",
    mapInput: (i) => ({ path: i.file_path, content: i.content }),
  },
  Edit: {
    to: "edit",
    mapInput: (i) => ({
      path: i.file_path,
      oldString: i.old_string,
      newString: i.new_string,
      ...(typeof i.replace_all === "boolean" ? { replaceAll: i.replace_all } : {}),
    }),
  },
  MultiEdit: {
    // Claude Code's MultiEdit applies several string-replace edits in order.
    // Botflow has no direct equivalent; the closest semantic match is
    // applyDiff with multiple SEARCH/REPLACE blocks. We convert each edit
    // pair into a block string.
    to: "applyDiff",
    mapInput: (i) => {
      const edits: Array<{ old_string: string; new_string: string }> =
        Array.isArray(i.edits) ? i.edits : [];
      const diff = edits
        .map(
          (e) =>
            `<<<<<<< SEARCH\n${e.old_string ?? ""}\n=======\n${e.new_string ?? ""}\n>>>>>>> REPLACE`,
        )
        .join("\n");
      return { path: i.file_path, diff };
    },
  },
  Bash: {
    to: "bash",
    mapInput: (i) => ({ command: String(i.command ?? "") }),
  },
  Grep: {
    to: "grep",
    mapInput: (i) => ({
      pattern: String(i.pattern ?? ""),
      ...(i.path ? { path: String(i.path) } : {}),
      ...(i.glob ? { glob: String(i.glob) } : {}),
      ...(i["-i"] || i.case_insensitive ? { caseInsensitive: true } : {}),
    }),
  },
  Glob: {
    to: "glob",
    mapInput: (i) => ({
      pattern: String(i.pattern ?? ""),
      ...(i.path ? { path: String(i.path) } : {}),
    }),
  },

  // ── Workspace control (identical names + shapes — passthrough) ───────
  startDevServer: passthrough("startDevServer"),
  stopDevServer: passthrough("stopDevServer"),
  isDevServerRunning: passthrough("isDevServerRunning"),
  getDevServerLog: {
    to: "getDevServerLog",
    mapInput: (i) => ({
      ...(typeof i.linesBack === "number" ? { linesBack: i.linesBack } : {}),
    }),
  },
  getBrowserLog: {
    to: "getBrowserLog",
    mapInput: (i) => ({
      ...(typeof i.linesBack === "number" ? { linesBack: i.linesBack } : {}),
    }),
  },
  refreshPreview: passthrough("refreshPreview"),

  // ── Convex MCP tool ──────────────────────────────────────────────────
  convex_deploy: {
    to: "convexDeploy",
    mapInput: identityInput,
  },

  // ── No Botflow counterpart — collapse to text summary on transit ─────
  Task: null,
  TodoWrite: null,
  WebFetch: null,
  WebSearch: null,
  NotebookEdit: null,
  BashOutput: null,
  KillShell: null,
  // Claude Code's internal end-turn marker — Botflow has its own endTurn but
  // we synthesize that locally per turn; replaying an old one would confuse
  // the next agent.
  endTurn: null,
};

/**
 * Botflow → Claude Code.
 * Not currently used as a runtime transform because Claude Code's bridge
 * doesn't take a messages array — we inject prior conversation as a text
 * preamble in the `prompt` field. Kept here for completeness and so future
 * work (e.g., true bidirectional message replay) has the shape ready.
 */
export const BOTFLOW_TO_CLAUDE_CODE: Record<string, ToolRewrite | null> = {
  read:        { to: "Read",  mapInput: (i) => ({ file_path: i.path }) },
  write:       { to: "Write", mapInput: (i) => ({ file_path: i.path, content: i.content }) },
  edit:        {
    to: "Edit",
    mapInput: (i) => ({
      file_path: i.path,
      old_string: i.oldString,
      new_string: i.newString,
      ...(typeof i.replaceAll === "boolean" ? { replace_all: i.replaceAll } : {}),
    }),
  },
  applyDiff:   null,
  bash:        { to: "Bash",  mapInput: (i) => ({ command: i.command }) },
  grep:        {
    to: "Grep",
    mapInput: (i) => ({
      pattern: i.pattern,
      ...(i.path ? { path: i.path } : {}),
      ...(i.glob ? { glob: i.glob } : {}),
    }),
  },
  glob:        { to: "Glob", mapInput: (i) => ({ pattern: i.pattern, ...(i.path ? { path: i.path } : {}) }) },
  listFiles:   null,
  endTurn:     null,
  // Workspace control + Convex
  startDevServer:      passthrough("startDevServer"),
  stopDevServer:       passthrough("stopDevServer"),
  isDevServerRunning:  passthrough("isDevServerRunning"),
  getDevServerLog:     passthrough("getDevServerLog"),
  getBrowserLog:       passthrough("getBrowserLog"),
  refreshPreview:      passthrough("refreshPreview"),
  convexDeploy:        { to: "convex_deploy", mapInput: identityInput },
};

/**
 * The set of tool names registered on the Botflow side (used to detect
 * "native" tool calls that need no rewriting). Keep this in sync with
 * `src/lib/agent/persistent-tools.ts` + `src/lib/agent/sandboxed-web-tools.ts`.
 */
export const BOTFLOW_NATIVE_TOOLS = new Set<string>([
  "bash",
  "read",
  "write",
  "edit",
  "applyDiff",
  "grep",
  "glob",
  "listFiles",
  "endTurn",
  "startDevServer",
  "stopDevServer",
  "isDevServerRunning",
  "getDevServerLog",
  "getBrowserLog",
  "refreshPreview",
  "convexDeploy",
]);

/** ID validation per Anthropic's tool_use_id constraint. */
export const TOOL_USE_ID_PATTERN = /^[a-zA-Z0-9_-]+$/;

/** Replace any characters outside the allowed set with `-` so a malformed
 *  legacy id doesn't crash a fresh API request. Deterministic, so retries
 *  remain idempotent. */
export function sanitizeToolUseId(id: string): string {
  if (!id) return "tool_unknown";
  if (TOOL_USE_ID_PATTERN.test(id)) return id;
  return id.replace(/[^a-zA-Z0-9_-]/g, "-");
}
